spring.application.name=emamura_ec
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/emamura_ec
spring.datasource.username=emamura_app
spring.datasource.password=emamura_dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true