-- =========================================
-- emamura_ec 初期テーブル定義
-- PostgreSQL
-- =========================================


-- 1. 会員
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    phone_number VARCHAR(20) NOT NULL,
    birth_date DATE,
    line_user_id VARCHAR(100) UNIQUE,

    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);


-- 2. 会員のお届け先
CREATE TABLE user_addresses (
    user_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipient_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    postal_code VARCHAR(8) NOT NULL,
    prefecture VARCHAR(10) NOT NULL,
    address_line VARCHAR(255) NOT NULL,

    CONSTRAINT fk_user_addresses_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);


-- 3. 商品カテゴリ
CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL UNIQUE
);


-- 4. 商品
CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price INTEGER NOT NULL,
    stock INTEGER NOT NULL,
    category_id BIGINT NOT NULL,
    description VARCHAR(1000),
    image_url VARCHAR(500),
    is_active BOOLEAN NOT NULL,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
);


-- 5. 配送地域
CREATE TABLE delivery_areas (
    delivery_area_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefecture VARCHAR(10) NOT NULL UNIQUE,
    shipping_fee INTEGER NOT NULL,
    lead_days INTEGER NOT NULL,
    available BOOLEAN NOT NULL
);


-- 6. 注文
CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_date TIMESTAMP NOT NULL,
    order_status VARCHAR(30) NOT NULL,
    subtotal INTEGER NOT NULL,
    shipping_fee INTEGER NOT NULL,
    paper_bag_count INTEGER NOT NULL,
    paper_bag_unit_price INTEGER NOT NULL,
    total_amount INTEGER NOT NULL,
    delivery_method VARCHAR(30) NOT NULL,
    requested_delivery_date DATE,
    payment_method VARCHAR(30) NOT NULL,

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);


-- 7. 注文明細
CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price INTEGER NOT NULL,
    wrapping_type VARCHAR(30) NOT NULL,
    ribbon_color VARCHAR(30) NOT NULL,
    message_text VARCHAR(30),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);


-- 8. 注文時のお届け先
CREATE TABLE order_addresses (
    order_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    recipient_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    postal_code VARCHAR(8) NOT NULL,
    prefecture VARCHAR(10) NOT NULL,
    address_line VARCHAR(255) NOT NULL,

    CONSTRAINT fk_order_addresses_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);


-- =========================================
-- 外部キー検索用インデックス
-- =========================================

CREATE INDEX idx_user_addresses_user_id
    ON user_addresses(user_id);

CREATE INDEX idx_products_category_id
    ON products(category_id);

CREATE INDEX idx_orders_user_id
    ON orders(user_id);

CREATE INDEX idx_order_items_order_id
    ON order_items(order_id);

CREATE INDEX idx_order_items_product_id
    ON order_items(product_id);
ALTER TABLE users
    ADD COLUMN role VARCHAR(20);

UPDATE users
SET role = 'USER'
WHERE role IS NULL;

ALTER TABLE users
    ALTER COLUMN role SET DEFAULT 'USER';

ALTER TABLE users
    ALTER COLUMN role SET NOT NULL;

UPDATE users
SET role = 'ADMIN'
WHERE email = 'issei@admin.com';